### ISSUE TITLE
PowerVR 8XE

### ISSUE THREAD

**Issue by who53** [openpvrsgx-devgroup/linux_openpvrsgx#15]
Hi,
My question might be annoying and maybe not related at all but I don't know where to ask. I have a Android tablet which have MT6761 PowerVR Rouge GE8300, I have ported droidian and ubuntu touch on it, And I heard the series 8 have mainline support, so I thought to backport it to my kernel instead of using old blobs and it might fix some GPU related problem of droidian and ubtouch. But I came across rouge docs in mainline that described that I need to have clock and interrupts in dts for it. But my current downstream kernel only have these entry
`mfg_clark@13000000 {
		compatible = "mediatek,clark";
		reg = <0 0x13000000 0 0x80000>;
		interrupts = <GIC_SPI 203 IRQ_TYPE_LEVEL_LOW>;
		interrupt-names = "RGX";
		clock-frequency = <570000000>;
	};
`
`gpufreq {
		compatible = "mediatek,mt6761-gpufreq";
		clocks =
			<&topckgen CLK_TOP_MFG_SEL>,
			<&topckgen CLK_TOP_MFGPLL>,
			<&clk26m>,
			<&scpsys SCP_SYS_MFG_ASYNC>,
			<&scpsys SCP_SYS_MFG>,
			<&scpsys SCP_SYS_MFG_CORE0>;
		clock-names =
			"clk_mux",
			"clk_main_parent",
			"clk_sub_parent",
			"mtcmos_mfg_async",
			"mtcmos_mfg",
			"mtcmos_mfg_core0";
	};
`

While a reference mainline dts is
`
gpu@fd00000 {
        compatible = "ti,am62-gpu", "img,img-axe";
        reg = <0x0fd00000 0x20000>;
        clocks = <&k3_clks 187 0>;
        clock-names = "core";
        interrupts = <GIC_SPI 86 IRQ_TYPE_LEVEL_HIGH>;
        power-domains = <&k3_pds 187 TI_SCI_PD_EXCLUSIVE>;
    };
`
Can you please give me some tips, I will be very grateful

**Comment by goldelico** [comment]
Hi Deepak,

> Am 07.08.2024 um 18:37 schrieb Deepak ***@***.***>:
> 
> 
> Hi,
> My question might be annoying and maybe not related at all but I don't know where to ask. I have a Android tablet which have MT6761 PowerVR Rouge GE8300, I have ported droidian and ubuntu touch on it, And I heard the series 8 have mainline support, so I thought to backport it to my kernel instead of using old blobs and it might fix some GPU related problem of droidian and ubtouch. But I came across rouge docs in mainline that described that I need to have clock and interrupts in dts for it. But my current downstream kernel only have these entry
> ***@***.*** { compatible = "mediatek,clark"; reg = <0 0x13000000 0 0x80000>; interrupts = <GIC_SPI 203 IRQ_TYPE_LEVEL_LOW>; interrupt-names = "RGX"; clock-frequency = <570000000>; }; 
> gpufreq { compatible = "mediatek,mt6761-gpufreq"; clocks = <&topckgen CLK_TOP_MFG_SEL>, <&topckgen CLK_TOP_MFGPLL>, <&clk26m>, <&scpsys SCP_SYS_MFG_ASYNC>, <&scpsys SCP_SYS_MFG>, <&scpsys SCP_SYS_MFG_CORE0>; clock-names = "clk_mux", "clk_main_parent", "clk_sub_parent", "mtcmos_mfg_async", "mtcmos_mfg", "mtcmos_mfg_core0"; };
> 
> While a reference mainline dts is
> ***@***.*** { compatible = "ti,am62-gpu", "img,img-axe"; reg = <0x0fd00000 0x20000>; clocks = <&k3_clks 187 0>; clock-names = "core"; interrupts = <GIC_SPI 86 IRQ_TYPE_LEVEL_HIGH>; power-domains = <&k3_pds 187 TI_SCI_PD_EXCLUSIVE>; };
> Can you please give me some tips, I will be very grateful
> 

Well, Rougue is a different architecture than SGX. And it recently has got mainline kernel support.
The Ubuntu images for the BeagleBoneAI-Y also appear to have drivers etc.

So you may analys the BBY image for a device tree entry: https://www.beagleboard.org/distros/beagley-ai-debian-12-5-2024-06-19-xfce

Alternatively you ca n look at the authors of the mainline driver and send them an e-mail.
Or you subscribe to the kernel mailing list (LKML) and post your questions there.

Just my 2cts,
Nikolaus

**Comment by who53** [comment]
Thankyou very much for the info :)
