### ISSUE TITLE
GPU crash?!

### ISSUE THREAD

**Issue by MightyM17** [openpvrsgx-devgroup/linux_openpvrsgx#4]
I was trying Sway with pmOS and the gpu and i got the following output - https://paste.ubuntu.com/p/9qxDDqkhgK/
The last error is `[ERROR] [GLES2] OpenGLES 2.0 API  generated error code 0x500(GL_INVALID_ENUM)` which makes me think that the gpu has crashed, can this be solved?

**Comment by xc-racer99** [comment]
You need the patch to wlroots from https://gitlab.com/postmarketOS/pmaports/uploads/db492f801c142af6ed80bf7afa91acff/0001-render-Don-t-use-GL_EXT_unpack_subimage-when-not-ava.patch

Basically wlroots uses an extension without checking for it (newer versions require the extension), and there's also a bug in the PowerVR code (I think) related to the border method that this patch also fixes (that's the GL_INVALID_ENUM that you're seeing).

**Comment by MightyM17** [comment]
Thanks a lot again @xc-racer99 this worked flawlessly :smile:

**Comment by MightyM17** [comment]
Hey @xc-racer99, the patch does not seem to work for the newer 0.14.0 wlroots. The seem to have changed `fmt->bpp` to `drm_fmt->bpp` but even that leads to errors for me.

**Comment by xc-racer99** [comment]
Have a peek at what @tmlind has to say at https://gitlab.com/postmarketOS/pmaports/-/issues/932#note_665411953 - his updated patches are way more likely to work :)

**Comment by MightyM17** [comment]
Thats great! Thanks

**Comment by MightyM17** [comment]
> Have a peek at what @tmlind has to say at https://gitlab.com/postmarketOS/pmaports/-/issues/932#note_665411953 - his updated patches are way more likely to work :)

Hey @xc-racer99 they dont seem to work for me, get the same GLES error :(

**Comment by xc-racer99** [comment]
> Hey @xc-racer99 they dont seem to work for me, get the same GLES error :(

Sorry, I don't really have the time for work on this at the moment.  Basically what is happening is that the PowerVR drivers don't support GL_EXT_unpack_subimage - so this causes issues that should be solved by https://github.com/tmlind/wlroots/commit/2ec83ab4f11b1f574d565bd04bbef2e55f154d76  Additionally, the GL_INVALID_ENUM errors were caused by some GL_CLAMP not being supported by PowerVR, I don't remember details offhand.
