### ISSUE TITLE
Beagleboard XM

### ISSUE THREAD

**Issue by jsorg71** [openpvrsgx-devgroup/linux_openpvrsgx#9]
I would like to update an old beableboard xm project to a newer kernel.
It has a DM3730 CPU with SGX 530 GPU.
I don't mind using 1.9 DDK but 1.14 would be nice.
Should this work?  What branch should I use?

**Comment by goldelico** [comment]
Hi,
DDK 1.14 should work well on DM3730. We had it running on the GTA04 using the same processor.

If you want to try some Debian image with the Letux kernel including the SGX driver, please try
https://projects.goldelico.com/p/gta04-makesd/
to bake a bootable SD card. There are several variants for Debian and Kernel releases.

If you want to compile a kernel from source, please try for example

https://git.goldelico.com/?p=letux-kernel.git;a=shortlog;h=refs/heads/pvrsrvkm-6.7-rc2

(or the same branch on github mirror:
https://github.com/openpvrsgx-devgroup/linux_openpvrsgx/tree/pvrsrvkm-6.7-rc2
)

Some hints how to build can be found here: https://github.com/openpvrsgx-devgroup/linux_openpvrsgx/wiki

If possible, please subscribe to the mailing list: ***@***.*** ***@***.***> which makes discussions and help a little easier.

BR,
Nikolaus

**Comment by jsorg71** [comment]
Thanks Nikolaus, I got it 1.14.3699939 working on a beagleboard xm!
I used the pvrsrvkm-v5.6 branch as the 1.14.3699939 kernel driver does not compile in the pvrsrvkm-6.7-rc2 branch.  1.17 does compile in the pvrsrvkm-6.7-rc2 branch, I think that is were the focus is.
I also had the omapdrm vs tilcdc issue with libsrv_um.so but the mailing list patch from you I think got it working.
I'll join the mailing list for any further discussion, thanks again for this awesome project.

**Comment by goldelico** [comment]
Hi,
that is great to hear!

As soon as I find time I'll take a look into the 1.14.3699939 compile issues. Most likely we have applied kernel-API changes only to 1.17 and some of them need a backport.

BR and Thanks,
Nikolaus

**Comment by goldelico** [comment]
Hi,
I have now fixed compile of newer kernel for 1.14.3699939 DDK by doing some backports
and tested on GTA04 (also DM3730) and I can load the firmware:

***@***.***:~# uname -a
Linux letux 6.7.0-letux+ #16199 SMP PREEMPT Mon Jan 15 15:42:24 CET 2024 armv7l GNU/Linux
***@***.***:~# cat /proc/pvr/version 
Version SGX_DDK sgxddk ***@***.*** (release) omap_sgx
System Version String: None
***@***.***:~# pvrsrvctl --start --no-module
[  815.105133] PVR_K: UM DDK-(3699939) and KM DDK-(3699939) match. [ OK ]
***@***.***:~# cat /proc/pvr/version 
Version SGX_DDK sgxddk ***@***.*** (release) omap_sgx
System Version String: SGX revision = 125
***@***.***:~# 

This will become part of pvrsrvkm-6.8-rc in some weeks.

BR and thanks,
Nikolaus

**Comment by jsorg71** [comment]
Thanks Nikolaus, I'll keep an eye out for it.
